### ISSUE TITLE
P2PK To cashAddress?

### ISSUE THREAD

**Issue by AdamSEY** [btccom/cashaddr-php#6]
is it possible to convert P2PK (Normal Address) to cashAddress?

**Comment by afk11** [comment]
Unfortunately not with the contents of this repository, you'll need something else for base58.

Our PHP sdk uses the `bitwasp/bitcoin` package, you can check out our AddressReader implementation. AddressReader serves to replace the static AddressFactory in the package, which is bitcoin specific. 

https://github.com/blocktrail/blocktrail-sdk-php/blob/b4bb25510b83d918ce3cd7ff27b7bc32969b42f7/src/Address/BitcoinCashAddressReader.php

Then we have this function that gracefully returns the cash address if a legacy address was provided. 
https://github.com/blocktrail/blocktrail-sdk-php/blob/b4bb25510b83d918ce3cd7ff27b7bc32969b42f7/src/BlocktrailSDK.php#L1780

If you're happy to use bitwasp/bitcoin feel free to poach the relevant code from the SDK, though there's a few classes you'll need to get it to work.

**Comment by AdamSEY** [comment]
Downloading whole these repositories is exhausting. adding this feature to your repository is much better than downloading BitWasp and Blocktrail.

**Comment by afk11** [comment]
I meant copy/paste, not import via composer.. And it would be scope creep to add base58 addresses to a repository named "cashaddress-php". I've already written base58 code, and it lives in bitcoin-php. The best I can do is bridging cashaddress-php and bitcoin-php with some other package.

**Comment by afk11** [comment]
Forgot to post this here, but there was finally a bridge published for bitcoin-php & BCH  https://github.com/btccom/bitwasp-bitcoin-bch-addon

**Comment by AdamSEY** [comment]
Yeah, I've seen that. I'm your big follower :)
